### ISSUE TITLE
Fetch the redirected url 

### ISSUE THREAD

**Issue by hasit** [Medium/medium-sdk-go#13]
I am writing a command line tool for publishing to Medium. This will be my first program where I access any API using golang.

I have followed the instructions until the point where I can build a url using secret state, redirect url, and scopes. 

    package main
    
    import (
    	"fmt"
    	"net/http"
    
    	"github.com/Medium/medium-sdk-go"
    )
    
    func check(e error) {
    	if e != nil {
    		panic(e)
    	}
    }
    
    func mediumAuth() {
    	m := medium.NewClient("clientIDString", "clientSecretString")
    
    	url := m.GetAuthorizationURL("supersecretstring", "http://hasit.me/callback/medium", medium.ScopeBasicProfile, medium.ScopePublishPost)

        //next step
    }

    
    func main() {
    	mediumAuth()
    }

The next step is to open the url to let user give permission for accessing his/her profile. I can successfully open the url.

    exec.Command("open", url).Start()

Now, once the user clicks on the url, how can I fetch the redirected url? I even tried using http GET but the response is not the one that I want.

    resp, err := http.Get(url)

Help will be appreciated. 

  [1]: https://github.com/Medium/medium-api-docs

**Comment by aki237** [comment]
This is what I did : 
```go
m := medium.NewClient("clientIDString", "clientSecretString")
url := m.GetAuthorizationURL("supersecretstring", "http://127.0.0.1:25000", medium.ScopeBasicProfile, medium.ScopePublishPost)
http.HandleFunc("/",somefunc)
go http.ListenAndServe(":25000",nil)
for !gotauthCode {}//gotauthcode is a global variable set to false
//When medium redirects to the url specified : 127.0.0.1:25000/ the somefunc
//will be called which does whatever it needs and sets this global variable to true.
```

**Comment by shitijagarwal** [comment]
@huckphin FYI

**Comment by hasit** [comment]
@aki237 looks good. I will try that get back to you if I run into more issues. Thank you for helping.

**Comment by aki237** [comment]
np
