### ISSUE TITLE
TestApiMethods is flaking

### ISSUE THREAD

**Issue by baris** [Medium/medium-sdk-go#8]
UploadImage generates MIME headers but their order may change (internally stored as a map).

**Comment by majelbstoat** [comment]
This is due to the multipart writer create part method being non-deterministic. There's a todo to solve this:

https://golang.org/src/mime/multipart/writer.go#L98

In the meantime, I may fall back to just building it all manually :disappointed:

**Comment by majelbstoat** [comment]
Fixed by #7.
